source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden','0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client','1.6.7'
gem 'nokogiri', '1.5.0'
gem 'mechanize'
gem 'mysql2'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate'
gem 'barby'
gem 'chunky_png'
gem 'mime-types', '1.23'
gem 'passenger','4.0.38'
