production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 encounter_privilege_map: Admit patient:Manage Patient Admissions,Admission diagnosis:Manage admission diagnoses,Discharge patient:Manage Patient Discharges,Discharge diagnosis:Manage Discharge Diagnoses,Lab orders:Manage Lab Orders,Update hiv status:Manage HIV Status Visits,Vitals:Manage Vitals,Give drugs:Manage Give Drugs
 create_from_remote: false
 use.user.selected.activities: false
 ipd.wards.tag: MPC Inpatient Wards
 show.patient.confirmation: true
 application_diagnosis_concept: QECH Emergency Diagnosis List
 advanced.prescription.interface: true
test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
