production:
   adapter: mysql
   database: openmrs17
   username: root
   password: yammyuk
   host: localhost

development:
  adapter: mysql
  database: bart2_development
  username: root
  password: root
  host: localhost

test: &TEST
  adapter: mysql
  database: openmrs15
  username: yamiko
  password: bart
  host: localhost

cucumber:
  <<: *TEST
